### ISSUE TITLE
DISCUSSION:How to avoid Browserify js overload

### ISSUE THREAD

**Issue by ginus** [StephanHoyer/mithril-isomorphic-example#3]
I noticed that the browser side js is less than 10KB, but the way browserify done is more than 100KB, it is overload. In your post in wiki I find you strat from a question "how to make a browser application become a Isomorphic application", then the solution is "browserify transform a node application run on browser" which is so diffrent of the start and end point. 
Can we have a solution that make a browser application run in node environment without any recode?
I mean that a gulp task flow like below:
browser application->gulp builds for performance->gulp build for node->node application.
Now in code time we can work as before in browser environment, better in runtime server side is node application and browser side is orign browser application.

**Comment by StephanHoyer** [comment]
The 100kb are only the browser code. But thats the develop build that includes source maps and is noch minified.

if you want to minify you have to run the App in production env. This can be done with setting the `NODE_ENV` environment variable when starting the app. So instead of

`$ node server.js`

you do 

`$ NODE_ENV=production node server.js`

That should minify the code.

**Comment by StephanHoyer** [comment]
just added a usage section to the readme
